spring:
  application:
    name: uj-file-uploader
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_ucb_judge}
    jpa:
      hibernate:
        ddl-auto: update

server:
  port: ${PORT:8083}

eureka:
  client:
    registerWithEureka: true
  serviceUrl:
    defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080/}
  autodetect-bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:BNHREThKV64GqdjrJKJqkmLLowtwjfSi}
  realm: ${KEYCLOAK_REALM:ucb-judge}
  resource: ${KEYCLOAK_CLIENT_ID:uj-problems}
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - upload-file
      security-collections:
        - name: Allow uploading files
          omitted-methods:
            - OPTIONS
          patterns:
            - /api/files/upload

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access:
    key: ${MINIO_ACCESS_KEY:iKOtBf9MN2CpPKsB}
    secret: ${MINIO_SECRET_KEY:Zrxoy7B2pv6FSXBOXIlCsNJcGFPZynPb}

